### ISSUE TITLE
请教TSM的输入尺寸问题

### ISSUE THREAD

**Issue by zzwei1** [zvict/tsm-vnet-debug#1]
你好，看到你也在看TSM，就想请教一下TSM的输入尺寸问题。
我有一组自己的数据来做手势识别（数据形式是这样的：每个手势有连续32帧图片），我的输入数据尺寸就是（N,C,T,H,W），但是我看TSM文章里，用2D-resnet做backbone,他要求的数据是4维的。请问我该怎么操作，才能匹配上输入尺寸呢？
我看TSM代码里，作者是（NT,C,H,W）这样一个维度，但是如果我直接x.view(NT,C,H,W)，那我的标签尺寸还是原来的N,还是对不上呢。

**Comment by zvict** [comment]
@zzwei1 你好，我觉得你可以参考ops/dataset.py里的get()，将标签也拓展到NT就行
